#!/usr/bin/env python3
"""Self-host the brand webfonts.

vornac.com must not open a connection to Google before the visitor has
consented (§ 25 TDDDG / GDPR — the LG München "Google Fonts" line of cases),
so the three brand families are served from our own origin instead of
fonts.googleapis.com / fonts.gstatic.com.

This script regenerates that local copy:

  1. asks the Google Fonts css2 API for the exact family/weight spec below,
     with a modern Chrome UA so we get woff2 back,
  2. keeps only the `latin` and `latin-ext` subsets (the site ships EN + DE;
     cyrillic / greek / vietnamese would be dead weight),
  3. downloads every .woff2 into fonts/ and rewrites the @font-face `src`
     to the local /fonts/… path,
  4. writes the result to fonts/fonts.css, which src/input.css @imports.

Run it again only when the type stack changes:

    python3 scripts/fetch_google_fonts.py
"""

from __future__ import annotations

import pathlib
import re
import sys
import urllib.parse
import urllib.request

# Same spec that used to sit in the <link> in src/_includes/partials/head-fonts.njk.
FAMILIES = [
    "Archivo:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,900",
    "Saira+Condensed:wght@500;600;700;800;900",
    "JetBrains+Mono:wght@400;500;700",
]
SUBSETS = {"latin", "latin-ext"}

# woff2 is only served to a UA that is known to support it.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "fonts"

BLOCK_RE = re.compile(
    r"/\*\s*(?P<subset>[a-z-]+)\s*\*/\s*(?P<block>@font-face\s*\{[^}]*\})",
    re.IGNORECASE,
)
SRC_RE = re.compile(r"url\((?P<url>https://fonts\.gstatic\.com/[^)]+)\)")
PROP_RE = lambda name: re.compile(rf"{name}\s*:\s*(?P<value>[^;]+);", re.IGNORECASE)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def prop(block: str, name: str) -> str:
    match = PROP_RE(name).search(block)
    return match.group("value").strip().strip("'\"") if match else ""


def local_name(block: str, subset: str, url: str) -> str:
    family = prop(block, "font-family").lower().replace(" ", "-")
    weight = prop(block, "font-weight") or "400"
    style = prop(block, "font-style") or "normal"
    suffix = "" if style == "normal" else f"-{style}"
    extension = pathlib.Path(urllib.parse.urlparse(url).path).suffix or ".woff2"
    return f"{family}-{weight}{suffix}-{subset}{extension}"


def main() -> int:
    css_url = (
        "https://fonts.googleapis.com/css2?"
        + "&".join(f"family={family}" for family in FAMILIES)
        + "&display=swap"
    )
    print(f"→ {css_url}")
    remote_css = fetch(css_url).decode("utf-8")

    OUT_DIR.mkdir(exist_ok=True)
    for stale in OUT_DIR.glob("*.woff2"):
        stale.unlink()

    faces: list[str] = []
    for match in BLOCK_RE.finditer(remote_css):
        subset = match.group("subset")
        if subset not in SUBSETS:
            continue
        block = match.group("block")
        src = SRC_RE.search(block)
        if not src:
            continue

        remote_url = src.group("url")
        filename = local_name(block, subset, remote_url)
        (OUT_DIR / filename).write_bytes(fetch(remote_url))
        print(f"  ✓ {filename}")

        faces.append(
            f"/* {subset} */\n"
            + block.replace(f"url({remote_url})", f"url(/fonts/{filename})")
        )

    if not faces:
        print("no @font-face blocks matched — did the css2 response change?", file=sys.stderr)
        return 1

    header = (
        "/* Self-hosted brand webfonts — DO NOT EDIT BY HAND.\n"
        "   Generated by scripts/fetch_google_fonts.py; see that file for why\n"
        "   these are served from our own origin instead of fonts.gstatic.com. */\n\n"
    )
    (OUT_DIR / "fonts.css").write_text(header + "\n\n".join(faces) + "\n")
    print(f"\n{len(faces)} faces → fonts/fonts.css")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
